# Generated by Django 4.2.7 on 2023-12-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0003_collection_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
