# Generated by Django 4.2.7 on 2023-12-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0004_alter_collection_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='quantity',
        ),
    ]
